// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CampusCoin.Models;

public partial class CampusCoinContext : DbContext
{
    public CampusCoinContext(DbContextOptions<CampusCoinContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserData> UserData { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserData>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK_UserData_1");

            entity.HasOne(d => d.User).WithMany(p => p.UserData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserData_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}