// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CampusCoin.Models;

public partial class CampusCoinContext : DbContext
{
    public CampusCoinContext(DbContextOptions<CampusCoinContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CDAD8C5E8");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);


            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(10);


            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);



            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);

        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}