// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CampusCoin.Models;

public partial class UserExpenseData
{
    [Key]
    [Column("ExpenseID")]
    public int ExpenseId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Category { get; set; }

    public int Amount { get; set; }

    [Column("Date Entered", TypeName = "datetime")]
    public DateTime DateEntered { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserExpenseData")]
    public virtual User User { get; set; }
}