// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CampusCoin.Models;

public partial class Users
{

    public Users(int UserId, string Email, string Password, string PhoneNumber, string FirstName, string LastName)
    {
        this.UserId = UserId;
        this.Email = Email;
        this.Password = Password;
        this.PhoneNumber = PhoneNumber;
        this.FirstName = FirstName;
        this.LastName = LastName;
    }

    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}